# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e15eaa7ec67beacc1f3c1fcb48c7bdc7807ea2bc7f1b199d0ef57232b076a2aa25e9313f7e3636d7bd79cef6f1a7dff94ec07eba115af95c814e59b31243c9b5

test:
  secret_key_base: dba1bdd3a8ae4d1f2d45de7bfa29b5b96b1fceefd3ca2cfed7fabf316376e52a0ec05076b49bbce1ab7cfc07f200abfc192618110488ec8e0a6438f637e6c4ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
